
export const bleDevices = [ { solicitedServiceUUIDs: null,
    isConnectable: false,
    serviceData: null,
    id: '819A9271-0445-7B3A-17FE-9388434A512D',
    localName: null,
    name: null,
    rssi: -70,
    mtu: 23,
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    manufacturerData: 'BgABCSACALTwIXZLLFftSAQSwbdDmPKgoFIScuc=',
    serviceUUIDs: null,
    _manager: null },
  { solicitedServiceUUIDs: null,
    name: null,
    rssi: -95,
    mtu: 23,
    txPowerLevel: null,
    overflowServiceUUIDs: null,
    isConnectable: false,
    serviceData: null,
    serviceUUIDs: null,
    id: 'C4C7E455-9EDB-909C-9DA5-13E6BC1AD81D',
    localName: null,
    manufacturerData: null,
    _manager: null },
  { localName: null,
    id: 'CEC733A8-FB02-6A33-D232-04D127ECFA3B',
    isConnectable: false,
    serviceData: null,
    name: null,
    serviceUUIDs: null,
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    mtu: 23,
    rssi: -87,
    solicitedServiceUUIDs: null,
    manufacturerData: 'BgABCSACLkuspu2ngyJerCpUXQ6yi0nwTXPjM1g=',
    _manager: null },
  { localName: null,
    id: '22A27035-8071-DBE8-BDBE-99D402100DF9',
    isConnectable: true,
    serviceData: null,
    name: null,
    serviceUUIDs: null,
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    mtu: 23,
    rssi: -75,
    solicitedServiceUUIDs: null,
    manufacturerData: null,
    _manager: null },
  { id: 'F0848D14-3143-D0D0-2C7E-4762624D836C',
    localName: null,
    solicitedServiceUUIDs: null,
    manufacturerData: null,
    rssi: -92,
    mtu: 23,
    name: null,
    isConnectable: true,
    serviceData: null,
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    serviceUUIDs: null,
    _manager: null },
  { localName: null,
    id: '98EC969A-030B-E584-7AE1-74533199D1CB',
    isConnectable: true,
    serviceData: null,
    name: null,
    serviceUUIDs: null,
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    mtu: 23,
    rssi: -60,
    solicitedServiceUUIDs: null,
    manufacturerData: null,
    _manager: null },
  { manufacturerData: null,
    localName: null,
    id: 'C35CE8FD-6452-AD23-B6A6-4BA5DD0C5EC2',
    serviceData: null,
    isConnectable: true,
    mtu: 23,
    rssi: 127,
    solicitedServiceUUIDs: null,
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    serviceUUIDs: null,
    name: null,
    _manager: null },
  { manufacturerData: 'BgABCSACbZdLWwjPsd+iX5kfCQhlYYaJdn9vq1o=',
    localName: null,
    id: '90F0B737-3895-6E53-9B53-962D79F7F76B',
    serviceData: null,
    isConnectable: false,
    mtu: 23,
    rssi: -95,
    solicitedServiceUUIDs: null,
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    serviceUUIDs: null,
    name: null,
    _manager: null },
  { serviceData: null,
    isConnectable: false,
    localName: null,
    id: '48A1D97A-29CD-E294-D198-0E0418E26B36',
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    serviceUUIDs: null,
    name: null,
    manufacturerData: 'BgABCSAChYfd9DUsm0Eo7Q5c59QVPSpNMGj8Ewg=',
    mtu: 23,
    rssi: -83,
    solicitedServiceUUIDs: null,
    _manager: null },
  { serviceData: null,
    isConnectable: false,
    localName: null,
    id: '939ECA46-9D2F-2F30-0082-3987B7809D80',
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    serviceUUIDs: null,
    name: null,
    manufacturerData: 'BgABCSEKLvpmGSj4REVTS1RPUC1ON0M3MFI4',
    mtu: 23,
    rssi: -71,
    solicitedServiceUUIDs: null,
    _manager: null },
  { localName: null,
    id: 'FF4D3147-B209-02AB-EF30-BB0E7748BA92',
    isConnectable: false,
    serviceData: null,
    serviceUUIDs: null,
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    name: null,
    solicitedServiceUUIDs: null,
    mtu: 23,
    rssi: -88,
    manufacturerData: 'BgABDyAC3Og8T3DLlSQElKvPokXe4cOkWqk/hSo=',
    _manager: null },
  { serviceData: null,
    isConnectable: true,
    localName: null,
    id: '926C5B2E-EC80-02B6-0076-C8F3183C6ADB',
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    serviceUUIDs: null,
    name: null,
    manufacturerData: null,
    mtu: 23,
    rssi: -58,
    solicitedServiceUUIDs: null,
    _manager: null },
  { manufacturerData: 'BgABCSACt+/AH1stHmWbvZ6kBdsOtjCRAj4mq3A=',
    localName: null,
    id: '4467BBD4-6307-5BA7-6F7E-D9D1B45D727C',
    serviceData: null,
    isConnectable: false,
    mtu: 23,
    rssi: -76,
    solicitedServiceUUIDs: null,
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    serviceUUIDs: null,
    name: null,
    _manager: null },
  { name: 'LE-reserved_C',
    mtu: 23,
    rssi: -92,
    solicitedServiceUUIDs: null,
    isConnectable: true,
    serviceData: null,
    id: 'F335E4AE-FAF8-A612-D9C8-58D7C8C29002',
    localName: 'LE-reserved_C',
    manufacturerData: 'AQsEAJ6snXtk',
    overflowServiceUUIDs: null,
    txPowerLevel: 8,
    serviceUUIDs: [ '0000febe-0000-1000-8000-00805f9b34fb' ],
    _manager: null },
  { localName: null,
    id: 'E3506F56-AA3F-4633-3B31-F738DCFBFD2D',
    serviceUUIDs: null,
    solicitedServiceUUIDs: null,
    rssi: -52,
    mtu: 23,
    txPowerLevel: null,
    overflowServiceUUIDs: null,
    isConnectable: true,
    serviceData: null,
    manufacturerData: null,
    name: null,
    _manager: null },
  { serviceUUIDs: [ '0000febe-0000-1000-8000-00805f9b34fb' ],
    name: 'LE-Bose Free SoundSport my',
    localName: 'LE-Bose Free SoundSport my',
    id: 'B2BAE8AC-D043-5103-27C7-9BEE4F271711',
    txPowerLevel: 8,
    overflowServiceUUIDs: null,
    isConnectable: true,
    serviceData: null,
    solicitedServiceUUIDs: null,
    mtu: 23,
    rssi: -89,
    manufacturerData: 'AQpEAKMlGH0b',
    _manager: null },
  { manufacturerData: null,
    solicitedServiceUUIDs: null,
    serviceData: { '0000fe9f-0000-1000-8000-00805f9b34fb': 'AAAAAAAAAAAAAAAAAAAAAAAAAAA=' },
    isConnectable: false,
    id: 'EC781E7E-BCC1-7B06-944D-F5F3EEC62937',
    serviceUUIDs: [ '0000fe9f-0000-1000-8000-00805f9b34fb' ],
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    rssi: -98,
    mtu: 23,
    name: null,
    localName: null,
    _manager: null },
  { id: '5BD4DB17-DCDD-4B11-33B5-6735B371AF45',
    localName: null,
    serviceUUIDs: [ '0000fe9f-0000-1000-8000-00805f9b34fb' ],
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    isConnectable: false,
    serviceData: { '0000fe9f-0000-1000-8000-00805f9b34fb': 'AAAAAAAAAAAAAAAAAAAAAAAAAAA=' },
    mtu: 23,
    rssi: -77,
    solicitedServiceUUIDs: null,
    manufacturerData: '4AAPnspWX38=',
    name: null,
    _manager: null },
  { id: '2FA5E975-5ED7-30B9-4C9E-BBEB13A23929',
    localName: null,
    serviceUUIDs: null,
    overflowServiceUUIDs: null,
    txPowerLevel: null,
    isConnectable: true,
    serviceData: null,
    mtu: 23,
    rssi: -95,
    solicitedServiceUUIDs: null,
    manufacturerData: null,
    name: null,
    _manager: null },
  { id: 'CBBF7006-85FE-C92D-6418-DF67C3C5D525',
    localName: null,
    solicitedServiceUUIDs: null,
    rssi: 127,
    mtu: 23,
    name: null,
    manufacturerData: 'BgABCSACM/taZOwMom/M8o6eOWbtjv4mlpeaB0w=',
    serviceData: null,
    txPowerLevel: null,
    overflowServiceUUIDs: null,
    serviceUUIDs: null,
    isConnectable: false,
    _manager: null },
  { localName: null,
    serviceUUIDs: null,
    isConnectable: true,
    serviceData: null,
    txPowerLevel: null,
    overflowServiceUUIDs: null,
    solicitedServiceUUIDs: null,
    rssi: -100,
    mtu: 23,
    name: null,
    manufacturerData: null,
    id: '1B5C4E49-B3EE-AB08-50D4-5D92C690E054',
    _manager: null } ]










