export const jobItem = {
  id: '915909bb-dc94-4158-acb0-714e81f124e2',
  type: 'Full Time',
  url: 'https://jobs.github.com/positions/915909bb-dc94-4158-acb0-714e81f124e2',
  created_at: 'Tue Jul 09 19:05:25 UTC 2019',
  company: 'Pattern',
  company_url: 'https://patternbrands.com/',
  location: 'New York City',
  title: 'Senior Full Stack Engineer',
  description: '<p>Full Stack Engineer</p>\n<p>Who we are\nLaunching in Summer 2019, Pattern is a family of brands on a mission to transform how you enjoy daily life. Our brands are intentionally designed to help you reclaim fulfillment in the process of making, shaping and doing.</p>\n<p>Pattern is led by Emmett Shine, Nick Ling, and a tested team of startup experts from Gin Lane. In the last decade with Gin Lane, they’ve built and scaled the foundation of over 50 digitally native vertical brands.</p>\n<p>We are based in Chinatown, New York and proudly backed by some of the most prominent investors in consumer goods.</p>\n<p>Job Description:\nYou will be joining Pattern’s engineering team as a Full Stack Engineer.  At Pattern we are always looking for teammates that are as passionate about our mission as we are - and most importantly can add to our culture of building amazing products.</p>\n<p>As engineers we value curiosity, respect, and feedback. And of course, shipping excellent code. We also put a ton of value on collaboration, mentorship and making sure everyone has a voice.</p>\n<p>We’re looking for someone who is not afraid to hit the ground running, and who is excited to play a key role in building Pattern Brands. Our team focuses on our end-user experience, internal tools, maintaining our systems and platforms, and operationalizing multiple brands and services across a single organization.</p>\n<p>This role reports to the VP of Engineering, Pattern Brands.</p>\n<p>Qualifications</p>\n<p>You will:</p>\n<ul>\n<li>Design and build new features that enable best in class commerce experience as well as unlock member benefits via best in class customer service</li>\n<li>Devise solutions to performance and scalability challenges as our customer data set continues to grow</li>\n<li>Use your passion for building great software to develop meaningful, delightful customer facing features that help our brands connect with and retain our members.</li>\n<li>Work closely with product management, design and internal teams to understand needs and develop solutions to improving operations and end-user experience</li>\n<li>Be pushed to stretch yourself by learning new technologies, system designs and paradigms</li>\n<li>Write high-quality, well-designed software that is well-tested and maintainable.</li>\n<li>Provide mentorship through code reviews and architecture discussions.</li>\n<li>Help recruit awesome engineers to expand our diverse team.</li>\n</ul>\n<p>You have:</p>\n<ul>\n<li>Knowledge of CS fundamentals and code organization</li>\n<li>A consistent track record of shipping quality software that positively impacts your end customer</li>\n<li>4+ years of software development experience or equivalent</li>\n<li>A bachelor’s degree in Computer Science or similar experience</li>\n<li>A strong sense of customer empathy and desire to influence the product direction</li>\n<li>Critical thinking, problem solving and analytical skills</li>\n</ul>\n<p>We work with:</p>\n<ul>\n<li>Service oriented, microservices and serverless architectures.</li>\n<li>Python, Ruby, or NodeJS</li>\n<li>React, Redux, modern Javascript/ECMAScript.</li>\n<li>Functional and OO paradigms</li>\n<li>Distributed systems architecture</li>\n<li>JEST, TestNG, or other Unit testing framework</li>\n<li>Web Service/API implementation</li>\n</ul>\n<p>What Pattern offers:</p>\n<ul>\n<li>Competitive compensation and meaningful equity</li>\n<li>Generous PTO Policy</li>\n<li>Company-sponsored medical and dental</li>\n<li>Commuter Benefits for Parking and Transit</li>\n<li>An amazing culture, team, and mission</li>\n<li>Breakfast every Monday, plus free drinks and snacks every day</li>\n<li>Company activities including happy hours, company BBQ’s, Town Halls, and more!</li>\n</ul>\n',
  how_to_apply: '<p>Email your resume to Talent: <a href="mailto:Julia@patternbrands.com">Julia@patternbrands.com</a></p>\n',
  company_logo: 'https://jobs.github.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmhyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2092546771cd36937e7ff7f90be438f454bd6828/pattern_logomark_emblem.png'
}

export const jobItemWithSkills = { id: '915909bb-dc94-4158-acb0-714e81f124e2',
  type: 'Full Time',
  url: 'https://jobs.github.com/positions/915909bb-dc94-4158-acb0-714e81f124e2',
  created_at: 'Tue Jul 09 19:05:25 UTC 2019',
  company: 'Pattern',
  company_url: 'https://patternbrands.com/',
  location: 'New York City',
  title: 'Senior Full Stack Engineer',
  description: '<p>Full Stack Engineer</p>\n<p>Who we are\nLaunching in Summer 2019, Pattern is a family of brands on a mission to transform how you enjoy daily life. Our brands are intentionally designed to help you reclaim fulfillment in the process of making, shaping and doing.</p>\n<p>Pattern is led by Emmett Shine, Nick Ling, and a tested team of startup experts from Gin Lane. In the last decade with Gin Lane, they’ve built and scaled the foundation of over 50 digitally native vertical brands.</p>\n<p>We are based in Chinatown, New York and proudly backed by some of the most prominent investors in consumer goods.</p>\n<p>Job Description:\nYou will be joining Pattern’s engineering team as a Full Stack Engineer.  At Pattern we are always looking for teammates that are as passionate about our mission as we are - and most importantly can add to our culture of building amazing products.</p>\n<p>As engineers we value curiosity, respect, and feedback. And of course, shipping excellent code. We also put a ton of value on collaboration, mentorship and making sure everyone has a voice.</p>\n<p>We’re looking for someone who is not afraid to hit the ground running, and who is excited to play a key role in building Pattern Brands. Our team focuses on our end-user experience, internal tools, maintaining our systems and platforms, and operationalizing multiple brands and services across a single organization.</p>\n<p>This role reports to the VP of Engineering, Pattern Brands.</p>\n<p>Qualifications</p>\n<p>You will:</p>\n<ul>\n<li>Design and build new features that enable best in class commerce experience as well as unlock member benefits via best in class customer service</li>\n<li>Devise solutions to performance and scalability challenges as our customer data set continues to grow</li>\n<li>Use your passion for building great software to develop meaningful, delightful customer facing features that help our brands connect with and retain our members.</li>\n<li>Work closely with product management, design and internal teams to understand needs and develop solutions to improving operations and end-user experience</li>\n<li>Be pushed to stretch yourself by learning new technologies, system designs and paradigms</li>\n<li>Write high-quality, well-designed software that is well-tested and maintainable.</li>\n<li>Provide mentorship through code reviews and architecture discussions.</li>\n<li>Help recruit awesome engineers to expand our diverse team.</li>\n</ul>\n<p>You have:</p>\n<ul>\n<li>Knowledge of CS fundamentals and code organization</li>\n<li>A consistent track record of shipping quality software that positively impacts your end customer</li>\n<li>4+ years of software development experience or equivalent</li>\n<li>A bachelor’s degree in Computer Science or similar experience</li>\n<li>A strong sense of customer empathy and desire to influence the product direction</li>\n<li>Critical thinking, problem solving and analytical skills</li>\n</ul>\n<p>We work with:</p>\n<ul>\n<li>Service oriented, microservices and serverless architectures.</li>\n<li>Python, Ruby, or NodeJS</li>\n<li>React, Redux, modern Javascript/ECMAScript.</li>\n<li>Functional and OO paradigms</li>\n<li>Distributed systems architecture</li>\n<li>JEST, TestNG, or other Unit testing framework</li>\n<li>Web Service/API implementation</li>\n</ul>\n<p>What Pattern offers:</p>\n<ul>\n<li>Competitive compensation and meaningful equity</li>\n<li>Generous PTO Policy</li>\n<li>Company-sponsored medical and dental</li>\n<li>Commuter Benefits for Parking and Transit</li>\n<li>An amazing culture, team, and mission</li>\n<li>Breakfast every Monday, plus free drinks and snacks every day</li>\n<li>Company activities including happy hours, company BBQ’s, Town Halls, and more!</li>\n</ul>\n',
  how_to_apply: '<p>Email your resume to Talent: <a href="mailto:Julia@patternbrands.com">Julia@patternbrands.com</a></p>\n',
  company_logo: 'https://jobs.github.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmhyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2092546771cd36937e7ff7f90be438f454bd6828/pattern_logomark_emblem.png',
  jobId: 'd2a703cbe4f6e2e3ec9034d99ba1fce4',
  relatedSkills: 
   [ { skill_uuid: 'c09c8f8c163907ac25a37c3dd591ba2e',
       skill_name: 'engineering and technology',
       skill_type: 'knowledge',
       description: 'knowledge of the practical application of engineering science and technology. this includes applying principles, techniques, procedures, and equipment to the design and production of various goods and services.',
       normalized_skill_name: 'engineering and technology',
       importance: 4.71,
       level: 6.42 },
     { skill_uuid: '8cfb10d3dd0ae49a87320653cbfa587e',
       skill_name: 'physics',
       skill_type: 'knowledge',
       description: 'knowledge and prediction of physical principles, laws, their interrelationships, and applications to understanding fluid, material, and atmospheric dynamics, and mechanical, electrical, atomic and sub- atomic structures and processes.',
       normalized_skill_name: 'physics',
       importance: 4.25,
       level: 5.62 },
     { skill_uuid: '6ae28a55456b101be8261e5dee44cd3e',
       skill_name: 'mathematics',
       skill_type: 'skill',
       description: 'using mathematics to solve problems.',
       normalized_skill_name: 'mathematics',
       importance: 4.21,
       level: 5.75 },
     { skill_uuid: 'dce09f281c35f49c2f58ea7580b530b7',
       skill_name: 'chemistry',
       skill_type: 'knowledge',
       description: 'knowledge of the chemical composition, structure, and properties of substances and of the chemical processes and transformations that they undergo. this includes uses of chemicals and their interactions, danger signs, production techniques, and disposal methods.',
       normalized_skill_name: 'chemistry',
       importance: 4.04,
       level: 5.48 },
     { skill_uuid: '19bec38cfa59f6542132b1ab155438c7',
       skill_name: 'written comprehension',
       skill_type: 'ability',
       description: 'the ability to read and understand information and ideas presented in writing.',
       normalized_skill_name: 'written comprehension',
       importance: 4,
       level: 4.75 },
     { skill_uuid: '2c77c703bd66e104c78b1392c3203362',
       skill_name: 'reading comprehension',
       skill_type: 'skill',
       description: 'understanding written sentences and paragraphs in work related documents.',
       normalized_skill_name: 'reading comprehension',
       importance: 3.88,
       level: 4.62 },
     { skill_uuid: '0194023051cb666af3d2c4761d894957',
       skill_name: 'oral comprehension',
       skill_type: 'ability',
       description: 'the ability to listen to and understand information and ideas presented through spoken words and sentences.',
       normalized_skill_name: 'oral comprehension',
       importance: 3.88,
       level: 4.62 },
     { skill_uuid: '01f0f8544779b7139f0152f2af679983',
       skill_name: 'written expression',
       skill_type: 'ability',
       description: 'the ability to communicate information and ideas in writing so others will understand.',
       normalized_skill_name: 'written expression',
       importance: 3.88,
       level: 4.38 },
     { skill_uuid: 'd66da8698b5a37186143205b78c73f7d',
       skill_name: 'problem sensitivity',
       skill_type: 'ability',
       description: 'the ability to tell when something is wrong or is likely to go wrong. it does not involve solving the problem, only recognizing there is a problem.',
       normalized_skill_name: 'problem sensitivity',
       importance: 3.88,
       level: 4.25 },
     { skill_uuid: '31c13f47ad87dd7baa2d558a91e0fbb9',
       skill_name: 'design',
       skill_type: 'knowledge',
       description: 'knowledge of design techniques, tools, and principles involved in production of precision technical plans, blueprints, drawings, and models.',
       normalized_skill_name: 'design',
       importance: 3.83,
       level: 5.29 },
     { skill_uuid: '20784bf09c9fe614603ad635e6093ede',
       skill_name: 'critical thinking',
       skill_type: 'skill',
       description: 'using logic and reasoning to identify the strengths and weaknesses of alternative solutions, conclusions or approaches to problems.',
       normalized_skill_name: 'critical thinking',
       importance: 3.75,
       level: 4.12 },
     { skill_uuid: 'b89f9a4fa693b12b7b72b19fc8f79160',
       skill_name: 'systems analysis',
       skill_type: 'skill',
       description: 'determining how a system should work and how changes in conditions, operations, and the environment will affect outcomes.',
       normalized_skill_name: 'systems analysis',
       importance: 3.75,
       level: 4 },
     { skill_uuid: '2ed46e9b35d1407c1ac983ddc6355fc8',
       skill_name: 'deductive reasoning',
       skill_type: 'ability',
       description: 'the ability to apply general rules to specific problems to produce answers that make sense.',
       normalized_skill_name: 'deductive reasoning',
       importance: 3.75,
       level: 4.12 },
     { skill_uuid: '3068a4aafb2a69ca31864655bb403e90',
       skill_name: 'inductive reasoning',
       skill_type: 'ability',
       description: 'the ability to combine pieces of information to form general rules or conclusions (includes finding a relationship among seemingly unrelated events).',
       normalized_skill_name: 'inductive reasoning',
       importance: 3.75,
       level: 4.12 },
     { skill_uuid: 'e72f8046dc4d704b6d1ca41dada93853',
       skill_name: 'mathematical reasoning',
       skill_type: 'ability',
       description: 'the ability to choose the right mathematical methods or formulas to solve a problem.',
       normalized_skill_name: 'mathematical reasoning',
       importance: 3.75,
       level: 4.25 },
     { skill_uuid: 'a636cb69257dcec699bce4f023a05126',
       skill_name: 'active listening',
       skill_type: 'skill',
       description: 'giving full attention to what other people are saying, taking time to understand the points being made, asking questions as appropriate, and not interrupting at inappropriate times.',
       normalized_skill_name: 'active listening',
       importance: 3.62,
       level: 4 },
     { skill_uuid: '1cea5345d284f36245a94301b114b27c',
       skill_name: 'writing',
       skill_type: 'skill',
       description: 'communicating effectively in writing as appropriate for the needs of the audience.',
       normalized_skill_name: 'writing',
       importance: 3.62,
       level: 4 },
     { skill_uuid: 'fb5c7f9bb4b32ce2f3bff4662f1ab27b',
       skill_name: 'science',
       skill_type: 'skill',
       description: 'using scientific rules and methods to solve problems.',
       normalized_skill_name: 'science',
       importance: 3.62,
       level: 3.88 },
     { skill_uuid: '76ff97c187542f8ff687cb51b1c3c416',
       skill_name: 'judgment and decision making',
       skill_type: 'skill',
       description: 'considering the relative costs and benefits of potential actions to choose the most appropriate one.',
       normalized_skill_name: 'judgment and decision making',
       importance: 3.62,
       level: 3.88 },
     { skill_uuid: 'd3dfdcdd96e1a57645c3b1728c640ee2',
       skill_name: 'oral expression',
       skill_type: 'ability',
       description: 'the ability to communicate information and ideas in speaking so others will understand.',
       normalized_skill_name: 'oral expression',
       importance: 3.62,
       level: 4.62 },
     { skill_uuid: 'e1a8c649e57ad7b1cfeef1aad5ba5c9c',
       skill_name: 'information ordering',
       skill_type: 'ability',
       description: 'the ability to arrange things or actions in a certain order or pattern according to a specific rule or set of rules (e.g., patterns of numbers, letters, words, pictures, mathematical operations).',
       normalized_skill_name: 'information ordering',
       importance: 3.62,
       level: 3.75 },
     { skill_uuid: 'd1715efc5a67ac1c988152b8136e3dfa',
       skill_name: 'speaking',
       skill_type: 'skill',
       description: 'talking to others to convey information effectively.',
       normalized_skill_name: 'speaking',
       importance: 3.5,
       level: 3.75 },
     { skill_uuid: '89948c7f4890af5ff18524b4fc3f3611',
       skill_name: 'monitoring',
       skill_type: 'skill',
       description: 'monitoring/assessing performance of yourself, other individuals, or organizations to make improvements or take corrective action.',
       normalized_skill_name: 'monitoring',
       importance: 3.5,
       level: 3.75 },
     { skill_uuid: 'a8005198cd137bfe2ea6d007f2ef40fe',
       skill_name: 'systems evaluation',
       skill_type: 'skill',
       description: 'identifying measures or indicators of system performance and the actions needed to improve or correct performance, relative to the goals of the system.',
       normalized_skill_name: 'systems evaluation',
       importance: 3.5,
       level: 4 },
     { skill_uuid: 'ed4e96dec61f1749fe26c4e6d576719a',
       skill_name: 'time management',
       skill_type: 'skill',
       description: 'managing one\'s own time and the time of others.',
       normalized_skill_name: 'time management',
       importance: 3.5,
       level: 3.5 },
     { skill_uuid: 'f6ae5e7ec49a12807ba61b1d547b120b',
       skill_name: 'fluency of ideas',
       skill_type: 'ability',
       description: 'the ability to come up with a number of ideas about a topic (the number of ideas is important, not their quality, correctness, or creativity).',
       normalized_skill_name: 'fluency of ideas',
       importance: 3.5,
       level: 4.12 },
     { skill_uuid: 'b37fe1c8f55d2b02b55a8e7846e74e8f',
       skill_name: 'category flexibility',
       skill_type: 'ability',
       description: 'the ability to generate or use different sets of rules for combining or grouping things in different ways.',
       normalized_skill_name: 'category flexibility',
       importance: 3.5,
       level: 3.5 },
     { skill_uuid: 'f2030d619ec0dc4f5b4ba9b8cd59ae99',
       skill_name: 'flexibility of closure',
       skill_type: 'ability',
       description: 'the ability to identify or detect a known pattern (a figure, object, word, or sound) that is hidden in other distracting material.',
       normalized_skill_name: 'flexibility of closure',
       importance: 3.5,
       level: 3.62 },
     { skill_uuid: '8d742521cd604d44c8ec58a6145e25ef',
       skill_name: 'selective attention',
       skill_type: 'ability',
       description: 'the ability to concentrate on a task over a period of time without being distracted.',
       normalized_skill_name: 'selective attention',
       importance: 3.5,
       level: 3.12 },
     { skill_uuid: '40d7109449763956696e4e2ef537a281',
       skill_name: 'near vision',
       skill_type: 'ability',
       description: 'the ability to see details at close range (within a few feet of the observer).',
       normalized_skill_name: 'near vision',
       importance: 3.5,
       level: 3.75 },
     { skill_uuid: 'b3cb1294905e001d3d611bff1de3962c',
       skill_name: 'computers and electronics',
       skill_type: 'knowledge',
       description: 'knowledge of circuit boards, processors, chips, electronic equipment, and computer hardware and software, including applications and programming.',
       normalized_skill_name: 'computers and electronics',
       importance: 3.5,
       level: 4.96 },
     { skill_uuid: '7e3fdeae0d52916ea5c86c7e5291f5be',
       skill_name: 'mechanical',
       skill_type: 'knowledge',
       description: 'knowledge of machines and tools, including their designs, uses, repair, and maintenance.',
       normalized_skill_name: 'mechanical',
       importance: 3.5,
       level: 4.54 },
     { skill_uuid: '87ba439073b69ab747d821d40b474fe6',
       skill_name: 'complex problem solving',
       skill_type: 'skill',
       description: 'identifying complex problems and reviewing related information to develop and evaluate options and implement solutions.',
       normalized_skill_name: 'complex problem solving',
       importance: 3.38,
       level: 3.5 },
     { skill_uuid: 'e98ada9866a495536ba6348ccec73915',
       skill_name: 'active learning',
       skill_type: 'skill',
       description: 'understanding the implications of new information for both current and future problem-solving and decision-making.',
       normalized_skill_name: 'active learning',
       importance: 3.38,
       level: 3.75 },
     { skill_uuid: '5cb21f7c94235e860596a2dfd90ccf82',
       skill_name: 'visualization',
       skill_type: 'ability',
       description: 'the ability to imagine how something will look after it is moved around or when its parts are moved or rearranged.',
       normalized_skill_name: 'visualization',
       importance: 3.38,
       level: 3.62 },
     { skill_uuid: '32707275e50c0b0e8dcc15b91df14252',
       skill_name: 'speech recognition',
       skill_type: 'ability',
       description: 'the ability to identify and understand the speech of another person.',
       normalized_skill_name: 'speech recognition',
       importance: 3.38,
       level: 3.5 },
     { skill_uuid: '0769a92e23352ccb05f9b452f8119972',
       skill_name: 'speech clarity',
       skill_type: 'ability',
       description: 'the ability to speak clearly so others can understand you.',
       normalized_skill_name: 'speech clarity',
       importance: 3.38,
       level: 3.38 },
     { skill_uuid: '1f360a397369faec034b8c7132a4b825',
       skill_name: 'learning strategies',
       skill_type: 'skill',
       description: 'selecting and using training/instructional methods and procedures appropriate for the situation when learning or teaching new things.',
       normalized_skill_name: 'learning strategies',
       importance: 3.25,
       level: 3.12 },
     { skill_uuid: 'a6cf24f6d3724019c1ae335987b4ce07',
       skill_name: 'operation monitoring',
       skill_type: 'skill',
       description: 'watching gauges, dials, or other indicators to make sure a machine is working properly.',
       normalized_skill_name: 'operation monitoring',
       importance: 3.25,
       level: 3.5 },
     { skill_uuid: '84eaacae3b4d0ea91b336e5ca738e407',
       skill_name: 'originality',
       skill_type: 'ability',
       description: 'the ability to come up with unusual or clever ideas about a given topic or situation, or to develop creative ways to solve a problem.',
       normalized_skill_name: 'originality',
       importance: 3.25,
       level: 3.75 },
     { skill_uuid: 'f1c31aa79acccfaefd2d776c37bacb4b',
       skill_name: 'perceptual speed',
       skill_type: 'ability',
       description: 'the ability to quickly and accurately compare similarities and differences among sets of letters, numbers, objects, pictures, or patterns. the things to be compared may be presented at the same time or one after the other. this ability also includes comparing a presented object with a remembered object.',
       normalized_skill_name: 'perceptual speed',
       importance: 3.25,
       level: 3.75 },
     { skill_uuid: '500018df958f2b9f8b387cf5637a0a04',
       skill_name: 'english language',
       skill_type: 'knowledge',
       description: 'knowledge of the structure and content of the english language including the meaning and spelling of words, rules of composition, and grammar.',
       normalized_skill_name: 'english language',
       importance: 3.25,
       level: 4.08 },
     { skill_uuid: '7ab99b9e2fd453d5eb2c8e2a7ea5aaa2',
       skill_name: 'quality control analysis',
       skill_type: 'skill',
       description: 'conducting tests and inspections of products, services, or processes to evaluate quality or performance.',
       normalized_skill_name: 'quality control analysis',
       importance: 3.12,
       level: 3.12 },
     { skill_uuid: 'b5e0d83efaba5d0f289021f7efbc77ed',
       skill_name: 'coordination',
       skill_type: 'skill',
       description: 'adjusting actions in relation to others\' actions.',
       normalized_skill_name: 'coordination',
       importance: 3.12,
       level: 3.12 },
     { skill_uuid: '809bcc13fd9a8517d2abefa4f15ed113',
       skill_name: 'number facility',
       skill_type: 'ability',
       description: 'the ability to add, subtract, multiply, or divide quickly and correctly.',
       normalized_skill_name: 'number facility',
       importance: 3.12,
       level: 3.62 },
     { skill_uuid: '7aff9d30fec0afd69aa17a77471a0f51',
       skill_name: 'far vision',
       skill_type: 'ability',
       description: 'the ability to see details at a distance.',
       normalized_skill_name: 'far vision',
       importance: 3.12,
       level: 3.25 },
     { skill_uuid: 'd75035dd61271431af6a9aabcc8b1b74',
       skill_name: 'persuasion',
       skill_type: 'skill',
       description: 'persuading others to change their minds or behavior.',
       normalized_skill_name: 'persuasion',
       importance: 2.88,
       level: 3.12 },
     { skill_uuid: '138848e0f8a20e554ba09affac47a7ab',
       skill_name: 'instructing',
       skill_type: 'skill',
       description: 'teaching others how to do something.',
       normalized_skill_name: 'instructing',
       importance: 2.88,
       level: 3.25 },
     { skill_uuid: '2962e937726316e39aa1e71a704f7bbb',
       skill_name: 'operations analysis',
       skill_type: 'skill',
       description: 'analyzing needs and product requirements to create a design.',
       normalized_skill_name: 'operations analysis',
       importance: 2.88,
       level: 3.12 },
     { skill_uuid: 'c7c0e2144032767d2c262fc7be7374e9',
       skill_name: 'technology design',
       skill_type: 'skill',
       description: 'generating or adapting equipment and technology to serve user needs.',
       normalized_skill_name: 'technology design',
       importance: 2.88,
       level: 3.25 },
     { skill_uuid: 'e09245effc62059e51f926fad603e413',
       skill_name: 'troubleshooting',
       skill_type: 'skill',
       description: 'determining causes of operating errors and deciding what to do about it.',
       normalized_skill_name: 'troubleshooting',
       importance: 2.88,
       level: 3.12 },
     { skill_uuid: '738a002b1aab0be6f74c025c369afdcf',
       skill_name: 'management of personnel resources',
       skill_type: 'skill',
       description: 'motivating, developing, and directing people as they work, identifying the best people for the job.',
       normalized_skill_name: 'management of personnel resources',
       importance: 2.88,
       level: 3.12 },
     { skill_uuid: '28c4f1558e2714bc24c83e8952c1ab10',
       skill_name: 'social perceptiveness',
       skill_type: 'skill',
       description: 'being aware of others\' reactions and understanding why they react as they do.',
       normalized_skill_name: 'social perceptiveness',
       importance: 2.88,
       level: 3.12 },
     { skill_uuid: 'eb5ef734480b6a225dc580eab22936b2',
       skill_name: 'speed of closure',
       skill_type: 'ability',
       description: 'the ability to quickly make sense of, combine, and organize information into meaningful patterns.',
       normalized_skill_name: 'speed of closure',
       importance: 2.88,
       level: 3 },
     { skill_uuid: '5d3842c4667b5120bda1d5e6bb68b0db',
       skill_name: 'visual color discrimination',
       skill_type: 'ability',
       description: 'the ability to match or detect differences between colors, including shades of color and brightness.',
       normalized_skill_name: 'visual color discrimination',
       importance: 2.88,
       level: 3.38 },
     { skill_uuid: 'ba4ebcd1fd8c42fe9792e043167fc012',
       skill_name: 'education and training',
       skill_type: 'knowledge',
       description: 'knowledge of principles and methods for curriculum and training design, teaching and instruction for individuals and groups, and the measurement of training effects.',
       normalized_skill_name: 'education and training',
       importance: 2.88,
       level: 3.75 },
     { skill_uuid: 'e84312809bee7cb3fc8663def614f2a4',
       skill_name: 'production and processing',
       skill_type: 'knowledge',
       description: 'knowledge of raw materials, production processes, quality control, costs, and other techniques for maximizing the effective manufacture and distribution of goods.',
       normalized_skill_name: 'production and processing',
       importance: 2.79,
       level: 3.42 },
     { skill_uuid: '15269137d10ab36461acfea127f6b5e8',
       skill_name: 'negotiation',
       skill_type: 'skill',
       description: 'bringing others together and trying to reconcile differences.',
       normalized_skill_name: 'negotiation',
       importance: 2.75,
       level: 2.88 },
     { skill_uuid: 'adb4921a45ae6bfee8768ff4a4cae80e',
       skill_name: 'service orientation',
       skill_type: 'skill',
       description: 'actively looking for ways to help people.',
       normalized_skill_name: 'service orientation',
       importance: 2.75,
       level: 2.88 },
     { skill_uuid: 'abb8d151fd50b5eac8ddb01842e8b72a',
       skill_name: 'time sharing',
       skill_type: 'ability',
       description: 'the ability to shift back and forth between two or more activities or sources of information (such as speech, sounds, touch, or other sources).',
       normalized_skill_name: 'time sharing',
       importance: 2.75,
       level: 2.75 },
     { skill_uuid: 'bccae81653386bf74cab10df63e11b12',
       skill_name: 'finger dexterity',
       skill_type: 'ability',
       description: 'the ability to make precisely coordinated movements of the fingers of one or both hands to grasp, manipulate, or assemble very small objects.',
       normalized_skill_name: 'finger dexterity',
       importance: 2.75,
       level: 2.88 },
     { skill_uuid: '3fbad295b55b92c44ede9bf1ba21861b',
       skill_name: 'control precision',
       skill_type: 'ability',
       description: 'the ability to quickly and repeatedly adjust the controls of a machine or a vehicle to exact positions.',
       normalized_skill_name: 'control precision',
       importance: 2.75,
       level: 2.75 },
     { skill_uuid: 'd3927ecfc36793d703f32ed919410ac5',
       skill_name: 'hearing sensitivity',
       skill_type: 'ability',
       description: 'the ability to detect or tell the differences between sounds that vary in pitch and loudness.',
       normalized_skill_name: 'hearing sensitivity',
       importance: 2.75,
       level: 2.75 },
     { skill_uuid: '307ea985e1f67ab0c3e7967d11d271b3',
       skill_name: 'public safety and security',
       skill_type: 'knowledge',
       description: 'knowledge of relevant equipment, policies, procedures, and strategies to promote effective local, state, or national security operations for the protection of people, data, property, and institutions.',
       normalized_skill_name: 'public safety and security',
       importance: 2.67,
       level: 2.96 },
     { skill_uuid: 'b452c459a4485c0e7fe1d71d79801f51',
       skill_name: 'repairing',
       skill_type: 'skill',
       description: 'repairing machines or systems using the needed tools.',
       normalized_skill_name: 'repairing',
       importance: 2.62,
       level: 2.75 },
     { skill_uuid: '959aeb423a004697059c4b2045c482cf',
       skill_name: 'management of material resources',
       skill_type: 'skill',
       description: 'obtaining and seeing to the appropriate use of equipment, facilities, and materials needed to do certain work.',
       normalized_skill_name: 'management of material resources',
       importance: 2.62,
       level: 2.88 },
     { skill_uuid: '30322e4301eaba3abd99d2a0509ef469',
       skill_name: 'memorization',
       skill_type: 'ability',
       description: 'the ability to remember information such as words, numbers, pictures, and procedures.',
       normalized_skill_name: 'memorization',
       importance: 2.62,
       level: 2.75 },
     { skill_uuid: '06eded9b1cfc0c29ca5ba434ca10a5ae',
       skill_name: 'arm-hand steadiness',
       skill_type: 'ability',
       description: 'the ability to keep your hand and arm steady while moving your arm or while holding your arm and hand in one position.',
       normalized_skill_name: 'armhand steadiness',
       importance: 2.62,
       level: 2.75 },
     { skill_uuid: '66e8dfe0d0591e65d8d1859ab74bfb22',
       skill_name: 'administration and management',
       skill_type: 'knowledge',
       description: 'knowledge of business and management principles involved in strategic planning, resource allocation, human resources modeling, leadership technique, production methods, and coordination of people and resources.',
       normalized_skill_name: 'administration and management',
       importance: 2.62,
       level: 3.17 },
     { skill_uuid: '035d26f14c0274510816c4f07c8ce8f3',
       skill_name: 'equipment selection',
       skill_type: 'skill',
       description: 'determining the kind of tools and equipment needed to do a job.',
       normalized_skill_name: 'equipment selection',
       importance: 2.5,
       level: 2.5 },
     { skill_uuid: '92b0b1a0a1f226bff3b26bf6bb85d25b',
       skill_name: 'operation and control',
       skill_type: 'skill',
       description: 'controlling operations of equipment or systems.',
       normalized_skill_name: 'operation and control',
       importance: 2.5,
       level: 2.88 },
     { skill_uuid: '1e1ab7995dc9dd14cc316049ad4f9d9e',
       skill_name: 'depth perception',
       skill_type: 'ability',
       description: 'the ability to judge which of several objects is closer or farther away from you, or to judge the distance between you and an object.',
       normalized_skill_name: 'depth perception',
       importance: 2.5,
       level: 2.5 },
     { skill_uuid: '4b6e11c46579a9cebec51d9038c58d10',
       skill_name: 'equipment maintenance',
       skill_type: 'skill',
       description: 'performing routine maintenance on equipment and determining when and what kind of maintenance is needed.',
       normalized_skill_name: 'equipment maintenance',
       importance: 2.38,
       level: 2.25 },
     { skill_uuid: '5814fda4d11918be93bcaa1381f29d63',
       skill_name: 'manual dexterity',
       skill_type: 'ability',
       description: 'the ability to quickly move your hand, your hand together with your arm, or your two hands to grasp, manipulate, or assemble objects.',
       normalized_skill_name: 'manual dexterity',
       importance: 2.38,
       level: 2.5 },
     { skill_uuid: '90ae790c9b6657437b8d069bf6ff4b9f',
       skill_name: 'auditory attention',
       skill_type: 'ability',
       description: 'the ability to focus on a single source of sound in the presence of other distracting sounds.',
       normalized_skill_name: 'auditory attention',
       importance: 2.38,
       level: 2.25 },
     { skill_uuid: '7e73d06707f5fb75ec77cc5f2bd9bb92',
       skill_name: 'programming',
       skill_type: 'skill',
       description: 'writing computer programs for various purposes.',
       normalized_skill_name: 'programming',
       importance: 2.25,
       level: 2 },
     { skill_uuid: '5f5513f407a612a546ba1d6fcea43c2c',
       skill_name: 'multilimb coordination',
       skill_type: 'ability',
       description: 'the ability to coordinate two or more limbs (for example, two arms, two legs, or one leg and one arm) while sitting, standing, or lying down. it does not involve performing the activities while the whole body is in motion.',
       normalized_skill_name: 'multilimb coordination',
       importance: 2.25,
       level: 1.75 },
     { skill_uuid: '4d70921065c00a293597936b693345aa',
       skill_name: 'transportation',
       skill_type: 'knowledge',
       description: 'knowledge of principles and methods for moving people or goods by air, rail, sea, or road, including the relative costs and benefits.',
       normalized_skill_name: 'transportation',
       importance: 2.12,
       level: 2.25 }]
}

export const jobItems = [{ id: 'd62aa6d3-9890-4e0a-804f-6bf57fb0a67d',
    type: 'Full Time',
    url: 'https://jobs.github.com/positions/d62aa6d3-9890-4e0a-804f-6bf57fb0a67d',
    created_at: 'Tue Jul 09 21:24:34 UTC 2019',
    company: 'Unified Compliance',
    company_url: 'http://www.unifiedcompliance.com',
    location: 'USA Virtual',
    title: 'Senior Software Engineer, Full-Stack',
    description: '<p>Design, develop and maintain the next generation of web applications and APIs for the Unified Compliance Framework (UCF).</p>\n<p>Position Summary\nThe UCF technology team is looking for a senior software engineer to help expand and maintain our patented product offerings.  We are dedicated to dramatically simplifying the process of regulatory compliance through robust products and APIs.</p>\n<p>The successful candidate will have a strong development background and a proven history taking a lead role in complex initiatives.  The work performed reaches across our entire technology stack, from databases, websites, cloud services, contact management, payment processing, natural language processing, and much more.</p>\n<p>We maintain a flat structure of technically-proficient personnel with an entirely remote workforce.  We will supply all the technology necessary to work from home.  This position is an Individual Contributor and reports directly to the CTO.</p>\n<p>Responsibilities</p>\n<ul>\n<li>Design, build, test, and deploy applications, features, and fixes</li>\n<li>Work with development team and non-developers to build new applications and improve/maintain existing ones</li>\n<li>Translate ideas, high-level or specific, into actionable tasks and complete them</li>\n<li>Participate in code review to maintain a high standard of quality, learn and grow as a development team</li>\n<li>Expand existing software to meet the changing needs of our key demographics</li>\n<li>Create fault-tolerant programming</li>\n<li>Create scalable, automated solutions for our customer base</li>\n<li>Write automated tests for new and existing code to ensure compatibility and stability</li>\n<li>Manage production releases and improve deployment processes and infrastructure\nQualifications</li>\n<li>5+ years experience developing software and web applications</li>\n<li>2+ years as a technical lead</li>\n<li>Experienced and comfortable with fundamental web technologies – HTML/CSS/JavaScript (ES6)</li>\n<li>Committed to good programming practices – unit and integration testing, version control, object-oriented design</li>\n<li>Proficient with Linux server environments and relational databases</li>\n<li>Comfortable with the Agile and Lean development process</li>\n<li>Entrepreneurial spirit and focus on delivering value into customers hands</li>\n<li>Focus on data-driven decision making and learning by experimentation.</li>\n<li>Ability to contribute anywhere in the stack and wear multiple hats.</li>\n<li>Self-starter, self-motivated, and willing to work on complex challenges.</li>\n<li>Able to write and speak clearly about complex systems and issues for both technical and layman audiences</li>\n</ul>\n<p>Preferred Qualifications</p>\n<ul>\n<li>PHP 7.x proficiency a big plus</li>\n<li>Zend Framework 2/3, Doctrine 2, AngularJS, D3, Clojure</li>\n<li>MySQL/PostgreSQL</li>\n<li>RESTful API development</li>\n<li>Natural Language Processing</li>\n<li>Amazon Web Services (Elastic Beanstalk, RDS, Elasticache (redis), EC2, etc)</li>\n<li>Docker</li>\n</ul>\n<p>About Us\nNetwork Frontiers is the creators of the Unified Compliance Framework (UCF), the premier database of laws, regulations, and other compliance requirements. UCF content is used throughout the GRC software landscape and is also licensed on an individual basis to corporate customers. Visit us at <a href="https://www.unifiedcompliance.com/">https://www.unifiedcompliance.com/</a>.</p>\n',
    how_to_apply: '<p>Email your resume to <a href="mailto:skohler@unifiedcompliance.com">skohler@unifiedcompliance.com</a></p>\n',
    company_logo: null },
  { id: '915909bb-dc94-4158-acb0-714e81f124e2',
    type: 'Full Time',
    url: 'https://jobs.github.com/positions/915909bb-dc94-4158-acb0-714e81f124e2',
    created_at: 'Tue Jul 09 19:05:25 UTC 2019',
    company: 'Pattern',
    company_url: 'https://patternbrands.com/',
    location: 'New York City',
    title: 'Senior Full Stack Engineer',
    description: '<p>Full Stack Engineer</p>\n<p>Who we are\nLaunching in Summer 2019, Pattern is a family of brands on a mission to transform how you enjoy daily life. Our brands are intentionally designed to help you reclaim fulfillment in the process of making, shaping and doing.</p>\n<p>Pattern is led by Emmett Shine, Nick Ling, and a tested team of startup experts from Gin Lane. In the last decade with Gin Lane, they’ve built and scaled the foundation of over 50 digitally native vertical brands.</p>\n<p>We are based in Chinatown, New York and proudly backed by some of the most prominent investors in consumer goods.</p>\n<p>Job Description:\nYou will be joining Pattern’s engineering team as a Full Stack Engineer.  At Pattern we are always looking for teammates that are as passionate about our mission as we are - and most importantly can add to our culture of building amazing products.</p>\n<p>As engineers we value curiosity, respect, and feedback. And of course, shipping excellent code. We also put a ton of value on collaboration, mentorship and making sure everyone has a voice.</p>\n<p>We’re looking for someone who is not afraid to hit the ground running, and who is excited to play a key role in building Pattern Brands. Our team focuses on our end-user experience, internal tools, maintaining our systems and platforms, and operationalizing multiple brands and services across a single organization.</p>\n<p>This role reports to the VP of Engineering, Pattern Brands.</p>\n<p>Qualifications</p>\n<p>You will:</p>\n<ul>\n<li>Design and build new features that enable best in class commerce experience as well as unlock member benefits via best in class customer service</li>\n<li>Devise solutions to performance and scalability challenges as our customer data set continues to grow</li>\n<li>Use your passion for building great software to develop meaningful, delightful customer facing features that help our brands connect with and retain our members.</li>\n<li>Work closely with product management, design and internal teams to understand needs and develop solutions to improving operations and end-user experience</li>\n<li>Be pushed to stretch yourself by learning new technologies, system designs and paradigms</li>\n<li>Write high-quality, well-designed software that is well-tested and maintainable.</li>\n<li>Provide mentorship through code reviews and architecture discussions.</li>\n<li>Help recruit awesome engineers to expand our diverse team.</li>\n</ul>\n<p>You have:</p>\n<ul>\n<li>Knowledge of CS fundamentals and code organization</li>\n<li>A consistent track record of shipping quality software that positively impacts your end customer</li>\n<li>4+ years of software development experience or equivalent</li>\n<li>A bachelor’s degree in Computer Science or similar experience</li>\n<li>A strong sense of customer empathy and desire to influence the product direction</li>\n<li>Critical thinking, problem solving and analytical skills</li>\n</ul>\n<p>We work with:</p>\n<ul>\n<li>Service oriented, microservices and serverless architectures.</li>\n<li>Python, Ruby, or NodeJS</li>\n<li>React, Redux, modern Javascript/ECMAScript.</li>\n<li>Functional and OO paradigms</li>\n<li>Distributed systems architecture</li>\n<li>JEST, TestNG, or other Unit testing framework</li>\n<li>Web Service/API implementation</li>\n</ul>\n<p>What Pattern offers:</p>\n<ul>\n<li>Competitive compensation and meaningful equity</li>\n<li>Generous PTO Policy</li>\n<li>Company-sponsored medical and dental</li>\n<li>Commuter Benefits for Parking and Transit</li>\n<li>An amazing culture, team, and mission</li>\n<li>Breakfast every Monday, plus free drinks and snacks every day</li>\n<li>Company activities including happy hours, company BBQ’s, Town Halls, and more!</li>\n</ul>\n',
    how_to_apply: '<p>Email your resume to Talent: <a href="mailto:Julia@patternbrands.com">Julia@patternbrands.com</a></p>\n',
    company_logo: 'https://jobs.github.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmhyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2092546771cd36937e7ff7f90be438f454bd6828/pattern_logomark_emblem.png' },
  { id: '568c59de-3991-4017-8594-229b8c6b9e1b',
    type: 'Full Time',
    url: 'https://jobs.github.com/positions/568c59de-3991-4017-8594-229b8c6b9e1b',
    created_at: 'Tue Jul 09 17:26:13 UTC 2019',
    company: 'SugarCRM',
    company_url: 'http://www.SugarCRM.com',
    location: 'Orlando, FL',
    title: 'Senior Software Engineer (Backend)',
    description: '<p>Where do you fit?</p>\n<p>SugarCRM is looking for a highly motivated, data-driven engineer with experience working on distributed systems. As an individual contributor of the engineering team, you will be responsible for designing and implementing new features, evolving our architecture, and improving operations. You understand the importance of code and design reviews, automated testing, and continuous delivery. Data informs the decisions you make and you can\'t imagine a world without metrics and instrumentation throughout the software systems you build. You have a passion for delivering amazing customer experiences, and enjoy participating in every level of product creation from ideation to pushing the final bits across the finish line.</p>\n<p>Impact you will make in the role:</p>\n<p>Design, enhance and build out new feature and services\nWork with engineering team to architect for scale and performance\nParticipate in code and design reviews, sprint plannings, and continuous releases\nWork with product and user experience teams to define and prototype new features\nDesign and build internal tools to monitor and maintain a SaaS infrastructure</p>\n<p>What you will need to succeed:</p>\n<p>5-10 years in software development using Java\n5-10 years developing web services as well as designing and working with API contracts across the stack\n2+ years experience with Linux/Unix and at least one scripting language\nSolid object-oriented principles and software design knowledge\nFundamental experience working on distributed systems\nExperience with at least one SQL and one NoSQL data store\nBS degree in Computer Science or related technical field or equivalent practical experience\nExperience successfully delivering complex software systems\nExperience building high performance, highly scalable and highly available distributed systems\nCommunication skills for both a technical and business audience\nExperience with Docker and Kubernetes\nExperience maintaining infrastructure on a major cloud provider\nExperience with Apache Spark\nExperience working in a startup environment</p>\n<p>Location:  Orlando, FL</p>\n<p>We are an Equal Opportunity, Affirmative Action employer. Minorities, women, veterans and individuals with disabilities are encouraged to apply.</p>\n<p>SugarCRM is not sponsoring immigration at this time.  Relocation assistance to Orlando, Florida is possible for the right candidate.</p>\n<p>Engineering Team Culture:</p>\n<p>Our focus is building out teams with smart engineers who are passionate about their craft and excited to build software for our unique solutions in the CX (customer experience) space. At SugarCRM, you\'ll have the chance to work on various teams and stacks. Here\'s more:</p>\n<p>Communication and collaboration is key to our processes, and we don\'t want to hinder it with walls\nWe are passionate about automated testing to deliver a high level of quality to our customers\nWe use a Scrum-based development methodology that includes daily stand-ups, regular Sprint reviews, and retrospectives to discuss\nWe value unique perspectives brought by diverse backgrounds and experiences. A broad range of ideas and perspectives help us to create the best possible product\nAs a part of our company culture, we encourage everyone to work at a healthy, sustainable pace</p>\n<p>Benefits and Perks:</p>\n<p>Beyond a stellar work environment, friendly people, and inspiring work, we have some great benefits and perks:</p>\n<p>Competitive salaries\nExcellent medical, dental and vision coverage for you and your family, along with other benefit plans like 401(k) match\nUnlimited paid time off policy\nHealth/Wellness:  Wellness Reimbursement\nCareer &amp; Personal Development Program – multi-platform\nNew Hire Onboarding for all new employees worldwide\nOwnership is the greatest self-identity at SugarCRM - you are making an impact now\nWe are a merit-based company - many opportunities to learn, excel and grow your career</p>\n',
    how_to_apply: '<p><a href="https://app.jobvite.com/j?cj=oxEeafwj&amp;s=Github_JobPost">https://app.jobvite.com/j?cj=oxEeafwj&amp;s=Github_JobPost</a></p>\n',
    company_logo: 'https://jobs.github.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblpyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bef426818d4edc26385d9ee17d64c68002661409/Full%20Color%20Logo_White%20Background_CMYK_Feb22_2016.png' },
  { id: 'dcbb96a2-6588-4acf-baa6-d064074ae9c0',
    type: 'Full Time',
    url: 'https://jobs.github.com/positions/dcbb96a2-6588-4acf-baa6-d064074ae9c0',
    created_at: 'Tue Jul 09 17:20:58 UTC 2019',
    company: 'SugarCRM',
    company_url: 'http://www.sugarcrm.com',
    location: 'Atlanta, GA',
    title: 'Senior Software Engineer',
    description: '<p>Where do you fit?</p>\n<p>As a Senior Software Engineer you will be a member of a talented and driven set of peers responsible for building and enhancing our core marketing automation platform. You are a technically proficient and solution-oriented Senior Software Engineer looking to make a major contribution in transforming the marketing automation industry. In this role, you will be architecting new software from the ground up and re-platforming existing applications.  You will be responsible for making sure these applications are robust, resilient, scalable and highly flexible.</p>\n<p>Impact you will make in the role:</p>\n<p>Guide team development efforts towards successful project delivery\nProvide technical guidance to teammates through coaching and mentorship\nDesign &amp; implement back-end architecture, from the data layer, to service orchestration\nRe-platform existing systems across tech stacks\nMaintain high standards of software quality within the team by establishing best practices\nCollaborate with other software engineers, product managers, and software architects to plan, design, develop, test, and maintain\nAdhere to high-quality modern lean engineering principles while delivering solutions on-time.\nPerform code reviews and mentor junior developers\nContinually look for ways to improve our code base and evaluate new technologies\nDeliver clean code and automated unit tests\nParticipate in functional requirements and design documentation</p>\n<p>What you will need to succeed:</p>\n<p>5+ years hands on working experience with development in ASP.NET, C#, SQL\nHands on working experience as a software architect designing and building systems from the ground up\nDesign and implementation of RESTful APIs, SaaS, system tasks and scalable cloud solutions\nStrong familiarity with and motivated to champion object oriented principles, design patterns, and SOLID principles\nWorking experience with Python\nExperience with .NET Core and C# development over Linux as well as Windows\nExperience with event frameworks (Kafka, Kinesis, RabbitMQ etc.)\nExposure to Agile methodologies\nExperience with automated testing frameworks (XUnit, Nose, Pytest)\nExperience with package management (nuget, myget)\nWorking experience with Microsoft IIS, Nginx, AWS, and Server Management\nComputer science degree or equivalently acquired knowledge</p>\n<p>Location:  Atlanta, GA</p>\n<p>We are an Equal Opportunity, Affirmative Action employer. Minorities, women, veterans, and individuals with disabilities are encouraged to apply.</p>\n<p>SugarCRM is not sponsoring immigration at this time.  We will provide relocation assistance to our Atlanta office, for the right candidate.</p>\n<p>Engineering Team Culture:</p>\n<p>Our focus is building out teams with smart engineers who are passionate about their craft and excited to build software for our unique solutions in the CX (customer experience) space. At SugarCRM, you\'ll have the chance to work on various teams and stacks. Here\'s more:</p>\n<p>Communication and collaboration is key to our processes, and we don\'t want to hinder it with walls\nWe are passionate about automated testing to deliver a high level of quality to our customers\nWe use a Scrum-based development methodology that includes daily stand-ups, regular Sprint reviews, and retrospectives to discuss\nWe value unique perspectives brought by diverse backgrounds and experiences. A broad range of ideas and perspectives help us to create the best possible product\nAs a part of our company culture, we encourage everyone to work at a healthy, sustainable pace</p>\n<p>Benefits and Perks:</p>\n<p>Beyond a stellar work environment, friendly people, and inspiring work, we have some great benefits and perks:</p>\n<p>Competitive salaries\nExcellent medical, dental and vision coverage for you and your family, along with other benefit plans like 401(k) match\nUnlimited paid time off policy\nHealth/Wellness:  Quarterly chair massages, Wellness Reimbursement, and Workforce Fitness Program\nCareer &amp; Personal Development Program – multi-platform\nNew Hire Onboarding for all new employees worldwide\nRegular social events and birthday celebrations (yes, sweet treats are a big deal at SugarCRM)\nOwnership is the greatest self-identity at SugarCRM - you are making an impact now\nWe are a merit-based company - many opportunities to learn, excel and grow your career</p>\n',
    how_to_apply: '<p><a href="https://app.jobvite.com/j?cj=oalfafwE&amp;s=Github_JobPost">https://app.jobvite.com/j?cj=oalfafwE&amp;s=Github_JobPost</a></p>\n',
    company_logo: 'https://jobs.github.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblJyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--af7ec6ac7285b79d0bb56397cf231970a13ed045/Full%20Color%20Logo_White%20Background_CMYK_Feb22_2016.png' },
  { id: 'cdaa783b-164a-4223-8497-cd6dd346055f',
    type: 'Full Time',
    url: 'https://jobs.github.com/positions/cdaa783b-164a-4223-8497-cd6dd346055f',
    created_at: 'Tue Jul 09 17:14:40 UTC 2019',
    company: 'SugarCRM',
    company_url: 'http://www.sugarcrm.com',
    location: 'Cupertino',
    title: 'Senior Software Engineer (Platform)',
    description: '<p>Where do you fit</p>\n<p>The SugarCRM platform team is responsible for creating robust, scalable, and highly performing technologies that drive our core CX (Customer Experience) offering.  You’ll be responsible for building new services and architectures while helping transform parts of our product lines into a robust and state of the art offering.  We are looking for exceptional engineers with a deep understanding of distributed systems, multi-language software development, and an understanding of what it takes to truly create an innovative platform that others can build on top of.</p>\n<p>So, if you are a motivated engineer looking to join a collaborative team, submit your application. You might be a perfect fit!</p>\n<p>Impact you will make in the role</p>\n<p>Development of the core application platform and framework\nProduce high-quality, readable, scalable, secure software that performs well, and at lightning speed using test-driven development\nFurther develop, optimize, refactor and understand our software architecture\nPush the envelope of software design and architecture\nChallenge, mentor and learn from your peers\nDesign reviews and code reviews to keep the standards high\nContinually sharpen your own skills</p>\n<p>Expertise you will bring in</p>\n<p>5+ years in software development\nFamiliarity with microservices architectures, messaging, loosely coupled design, NoSQL / relational databases, Restful APIS and protobuf\nMust be able to adapt to a fast-paced collaborative environment\nStrong written and verbal communication abilities, flexibility, and commitment to meet deadlines are a must\nExperience developing CRM applications a plus</p>\n<p>Location: Cupertino, CA</p>\n<ul>\n<li>SugarCRM is not sponsoring immigration at this time. Relocation to the San Francisco Bay Area will be supported for the right candidate. *</li>\n</ul>\n<p>Benefits and Perks:</p>\n<p>Beyond a stellar work environment, friendly people, and inspiring work, we have some great benefits and perks:</p>\n<p>Competitive salaries\nExcellent medical, dental and vision coverage for you and your family, along with other benefit plans including 401(k) match\nUnlimited Paid Time Off\nWeekly catered lunch &amp; learns, fully stocked kitchens, and nearby access to Cupertino’s newest restaurants and stores at Main Street Cupertino\nWellness Reimbursement Program\nOnsite Programs, depending on location, such as Dry Cleaning, Car Washes, Massage, Yoga, and more\nCareer &amp; Personal Development Program – multi-platform\nNew Hire Onboarding for all new employees worldwide\nRegular social events\nOwnership is the greatest self-identity at SugarCRM - you are making an impact now\nWe are a merit-based company - many opportunities to learn, excel and grow your career</p>\n<p>We are an Equal Opportunity, Affirmative Action employer. Minorities, women, veterans and individuals with disabilities are encouraged to apply.</p>\n',
    how_to_apply: '<p><a href="https://app.jobvite.com/j?cj=oX489fw2&amp;s=Github_JobPost">https://app.jobvite.com/j?cj=oX489fw2&amp;s=Github_JobPost</a></p>\n',
    company_logo: 'https://jobs.github.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkpyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--687350130627c642cdcdb00ccd8de4e660750073/Full%20Color%20Logo_White%20Background_CMYK_Feb22_2016.png' },
  { id: '915a48e4-0fbd-46f4-9a8a-7e70b8de97fa',
    type: 'Full Time',
    url: 'https://jobs.github.com/positions/915a48e4-0fbd-46f4-9a8a-7e70b8de97fa',
    created_at: 'Tue Jul 09 15:23:16 UTC 2019',
    company: 'Analysis and Measurement Services Corporation',
    company_url: 'http:',
    location: 'Knoxville, TN',
    title: 'LabVIEW Software Developer',
    description: '<p>DESIRED REQUIREMENTS</p>\n<ul>\n<li>A Bachelor or Master of Science degree in Computer Science, Electrical Engineering or other Engineering and/or 5 years of experience in software development and testing.</li>\n<li>2-3 years experience developing software applications in LabVIEW</li>\n<li>Experience in data acquisition using National Instruments-based hardware systems (daqmx, cRIO, cDAQ, and PXI)</li>\n</ul>\n<p>RESPONSIBILITIES</p>\n<ul>\n<li>Design and develop software products</li>\n<li>Perform software verification and validation</li>\n<li>Perform research and development to design new test equipment and technology</li>\n<li>Compile data and write reports for completed projects</li>\n<li>Perform other work as assigned by company management</li>\n<li>Maintain an orderly and professional appearance</li>\n</ul>\n',
    how_to_apply: '<p>To apply, please go to <a href="http://ams-careers.com/software-developers/">http://ams-careers.com/software-developers/</a>.</p>\n',
    company_logo: 'https://jobs.github.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTVyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e32e9deef435ea20765c9f51ea529f90dfd0b310/AMS%20Logo-Color.jpg' },
  { id: '671b0716-2e11-48bb-bbcf-5018780b79cf',
    type: 'Full Time',
    url: 'https://jobs.github.com/positions/671b0716-2e11-48bb-bbcf-5018780b79cf',
    created_at: 'Tue Jul 09 15:14:50 UTC 2019',
    company: 'Analysis and Measurement Services Corporation',
    company_url: 'http://www.ams-corp.com/',
    location: 'Knoxville, TN',
    title: 'Delphi Software Developer',
    description: '<p>DESIRED REQUIREMENTS</p>\n<ul>\n<li>A Bachelor or Master of Science degree in Computer Science, Electrical Engineering or other Engineering and/or 5 years of experience in software development and testing.</li>\n<li>Experience developing software applications in Delphi</li>\n<li>3-5 years experience in creating and using SQL databases to store and search data</li>\n</ul>\n<p>RESPONSIBILITIES</p>\n<ul>\n<li>Design and develop software products</li>\n<li>Perform software verification and validation</li>\n<li>Perform research and development to design new test equipment and technology</li>\n<li>Compile data and write reports for completed projects</li>\n<li>Perform other work as assigned by company management</li>\n<li>Maintain an orderly and professional appearance</li>\n</ul>\n',
    how_to_apply: '<p>To apply, go to <a href="http://ams-careers.com/delphi-software-developer/">http://ams-careers.com/delphi-software-developer/</a>.</p>\n',
    company_logo: 'https://jobs.github.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXhyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1fac04837b92c5fb3841b420d3a7e9c88c86cd29/AMS%20Logo-Color.jpg' },
  { id: '2af9670b-7cfa-4437-ba54-0efe8fd3c506',
    type: 'Full Time',
    url: 'https://jobs.github.com/positions/2af9670b-7cfa-4437-ba54-0efe8fd3c506',
    created_at: 'Tue Jul 09 15:09:35 UTC 2019',
    company: 'New Visions for Public Schools',
    company_url: 'https://www.newvisions.org/',
    location: 'New York City',
    title: 'Lead Product Designer',
    description: '<p><strong>Summary</strong></p>\n<p>New Visions for Public Schools is dedicated to empowering school leaders, teachers, and administrators with modern technology to effectively manage the complex work of teaching and learning.</p>\n<p>Our digital products include the New Visions Data Portal, a comprehensive school management platform, used by over 350 NYC schools, as well as some of the most popular Add-ons in the GSuite marketplace (Doctopus, autoCrat, formMule, and many more), which have helped thousands of teachers around the world simplify their workflow, personalize their feedback, and communicate more efficiently with students and families.</p>\n<p>Schools have specific and limited opportunities over the course of the school year to engage in a set of high stakes activities that will impact student outcomes, such as programming, academic interventions, and postsecondary planning.  Our Data Portal helps schools seize every opportunity for student success -- alerting educators to critical changes in student performance, nudging staff to take specific actions, and tracking student progress in interventions. Our goal is to simplify complex managerial challenges so that school leaders and educators can focus on supporting their students to graduate and succeed beyond high school.</p>\n<p>We\'re looking for a thoughtful and passionate Lead Product Designer to join our team. You will work directly with product managers, designers, and stakeholders to solve the most complex problems in urban K-12 education, and with engineers to build performant, user-centric products our educators will love. You will lead and mentor a team of designers, managing the day-to-day work of the team as well as supporting the career growth of team members. You will learn and grow alongside your colleagues in a highly collaborative, mission-driven environment.</p>\n<p><strong>Key Responsibilities</strong></p>\n<ul>\n<li>Lead the product design process and decision-making including planning, prioritizing, and establishing realistic timelines for projects.</li>\n<li>Collaborate closely with product managers and senior leadership to create solutions that achieve business and end user goals.</li>\n<li>Supervise, mentor and support the career growth of design team members.</li>\n<li>Lead user research and usability testing initiatives to iterate on product solutions.</li>\n<li>Lead design review sessions and cycle of feedback, revisions, etc.</li>\n<li>Ensure consistency across all of our products &amp; integrations by working within our established design system and making updates where necessary.</li>\n</ul>\n<p><strong>Must Haves</strong></p>\n<ul>\n<li>Bachelor’s Degree</li>\n<li>Online portfolio with case studies of relevant UX/UI projects that demonstrates a history of successful design implementations</li>\n<li>5+ years of professional experience in UX design, prototyping, visual design, and user research, including 2+ years managing designers</li>\n<li>Experience working in a cross-functional Agile development process, such as Scrum or Kanban</li>\n<li>Advanced knowledge of web standards and UX best practices</li>\n<li>Advanced knowledge of typography, information hierarchy, color, and other UI concerns</li>\n<li>Advanced knowledge of leading design software, including Sketch, Zeplin, and Adobe Creative - - - - Cloud and experience documenting designs</li>\n<li>Strong understanding of web capabilities, including HTML, CSS, and Javascript.</li>\n</ul>\n<p><strong>Skills</strong></p>\n<ul>\n<li>You are a mentor and a leader</li>\n</ul>\n<p>You enjoy managing and training team members and understand how to maximize each team member’s unique skills and strengths. You are skilled at accomplishing things through other people while helping them to grow. You can provide leadership for peers, subordinates, and partners, and know how to communicate ideas to get teams aligned and moving forward together.</p>\n<ul>\n<li>You ask the right questions</li>\n</ul>\n<p>At every stage of the design process you know what questions to ask. During the discovery phase, you are adept at probing for underlying assumptions and honing in on the true problem.  You know how to lead user research initiatives to get past surface-level issues and identify the underlying causes of user needs. During the prototyping and wireframing phase, you know how to lead design critiques and usability tests that help designers identify solution improvements.  When presenting designs, you are able to interrogate responses from stakeholders to help us collect deeper, more insightful feedback.</p>\n<ul>\n<li>You love data</li>\n</ul>\n<p>You are skilled at extracting answers from both qualitative and quantitative data.  You have a have strong organizational and analytical thinking skills, with a track record of breaking down complex content into manageable chunks.  You are comfortable examining data, determining what’s important, noting patterns, and coming to conclusions.</p>\n<ul>\n<li>You see the big picture</li>\n</ul>\n<p>You enjoy thinking about how to improve the product over the long-term, but are able to balance this vision for the future with short-term product design needs.  You are able to rapidly produce multiple concepts and prototypes, and know when to apply high-fidelity detail, and when to make low-fi sketches and prototypes.</p>\n<ul>\n<li>You thrive on collaboration</li>\n</ul>\n<p>You\'re excited to work cross-functionally with other teams and you’re skilled at establishing and cultivating strong relationships with all types of people.  You have a positive attitude, a sense of humor, and can help the team navigate high stress situations. You are willing to give and accept constructive criticism and rapidly adapt to feedback.</p>\n<p><strong>Nice to Haves</strong></p>\n<ul>\n<li>Knowledge of NYC school system</li>\n<li>Advanced knowledge of Javascript</li>\n<li>Experience with Git, Vue and/or Angular</li>\n</ul>\n<p><em>New Visions for Public Schools is an equal opportunity employer.</em></p>\n',
    how_to_apply: '<p>To apply, please submit an application on our\n<a href="https://www.newvisions.org/pages/Central-Office-Careers?gh_jid=1747354">Careers Site</a></p>\n',
    company_logo: 'https://jobs.github.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXByIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fb5ae0a6f31d8b44cc99d8d3e8edbcf00d47a9a8/NVPS%20Logo%20Primary.jpg' },]

export const jobItemsWithSkills = [jobItemWithSkills, ...jobItems]












